name: Render Verification Report

on:
  push:
    paths:
      - 'measure_datasets/**'

jobs:
  render-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c(
          'dplyr',
          'gt',
          'readr',
          'countyhealthR',
          'quarto'
          ))"

      - name: Render report
        run: |
          quarto render verification/verification.qmd --to html