name: Test Measure Dataset Trigger

on:
  push:
  paths:
  - 'measure_datasets/**'

jobs:
  print-changed-files:
  runs-on: ubuntu-latest

steps:
  - name: Checkout repo
uses: actions/checkout@v4
with:
  fetch-depth: 2

- name: Print changed files
run: |
  echo "Changed files:"
git diff --name-only HEAD~1 HEAD